class Boxy:
    def __init__(self, box_type: str, color: str) -> None: ...
    def add_text_sgmt(self, text: str, color: str, align: str) -> None: ...
    def add_text_line(self, text: str, color: str) -> None: ...
    def add_text_line_indx(self, text: str, color: str, seg_index: int) -> None: ...
    def add_col_text_sgmt(self, align: str, column_count: int) -> None: ...
    def add_col_text_line(self, text: str, color: str, col_index: int) -> None: ...
    def add_col_text_line_indx(self, text: str, color: str, seg_index: int, col_index: int) -> None: ...
    def set_align(self, align: str) -> None: ...
    def set_padding(self, internal: int, external: int) -> None: ...
    def set_segment_ratios(self, seg_index: int, ratios: list[int]) -> None: ...
    def render(self, width: int) -> list[str]: ...
    def display(self) -> None: ...

__version__: str
